Dictionary/apps/dict/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.TensesViews.as_view(), name='Tenses_list'),
    path("<slug:slug>/", views.TensesDitail.as_view(), name='tense_detail'),
    path("review/<int:pk>/", views.PrhaseAdd.as_view(), name='add_phrase'),
]

Dictionary/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dict.urls')),
]

Dictionary/apps/dict/models.py
from django.db import models
from django.urls import reverse


class Tenses(models.Model):
    name = models.CharField('Tense', max_length=30)
    descriptions = models.TextField(max_length=150)
    t_form = models.BooleanField(null=True, default=False)
    url = models.SlugField(max_length=1602, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("tense_detail", kwargs={'slug': self.url})

    class Meta:
        verbose_name = 'Tense'
        verbose_name_plural = 'Tenses'


class Phrase(models.Model):
    engphrase = models.CharField(max_length=30)
    translate = models.CharField(max_length=40, help_text='Enter your phrase is translate')
    gold_phrase = models.BooleanField('Золотой слиток',null=True, default=False)
    tenses = models.ForeignKey(Tenses, verbose_name='Tenses', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Phrase'
        verbose_name_plural = 'Phrases'

Dictionary/apps/dict/forms.py
from django import forms
from .models import Phrase, Tenses

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Phrase
        fields = ('engphrase', 'translate')

Dictionary/apps/dict/views.py
from django.shortcuts import render, redirect
from .models import Tenses, Phrase
from django.views.generic import ListView, DetailView
from django.views.generic.base import View
from .forms import ReviewForm

class TensesViews(ListView):
    model = Tenses
    queryset = Tenses.objects.all()
    context_object_name = 'tenses'
    template_name = 'dict/index.html'

class TensesDitail(DetailView):
    model = Tenses
    slug_field = 'url'
    context_object_name = 'dict'
    template_name = 'dict/list_dict.html'

class PrhaseAdd(View):
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        dicti = Tenses.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.tenses = dicti
            form.save()
        return redirect(dicti.get_absolute_url())

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--/ Style-CSS -->
    <link rel="stylesheet" href="{% static 'css/style_dict.css' %}" type="text/css" media="all">
    <!--// Style-CSS -->

    <title> {% block title %}{% endblock %} </title>
</head>
<body>
    {% include 'include/header.html' %}

    {% block content %}
        <div class="container">
        </div>
    {% endblock content %}

    {% include 'include/footer.html' %}

</body>
</html>

templates/dict/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="intro">
     <div class="container">
        <div class="intro_inner">
            <h2 class="intro_title">Happy Hope</h2>
        </div>
        <div class="intro_table">
            <table class="sub_table" border="1px">
                <tr>
                    <th></th>
                    <th>past simple</th>
                    <th>present simple</th>
                    <th>future simple</th>
                </tr>
                <tr>
                    <th>Вообще просто <br> происходит</th>
                    <th>was/were</th>
                    <th>am/is/are</th>
                    <th>will be</th>
                </tr>
                <tr>
                    <th>Есть результат</th>
                    <th>был до тогда</th>
                    <th>have/has been</th>
                    <th>побуду до тогда</th>
                </tr>

            </table>
            <div>
                {% for i in tenses %}
                <a href="{{ i.get_absolute_url }}">{{i.name}}</a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/dict/list_dict.html
{% extends 'base.html' %}
    {% block title %}
        {{ dict.name }}
    {% endblock %}
{% block content %}
<div class="intro">
    <div class="container">
        <div class="intro_inner">
            <h2 class="intro_title">Happy Hope</h2>
        </div>
        <div class="intro_table">
            <table class="sub_table" border="1px">
                <tr>
                    <th></th>
                    <th>past simple</th>
                    <th>present simple</th>
                    <th>future simple</th>
                </tr>
                <tr>
                    <th>Вообще просто <br> происходит</th>
                    <th>was/were</th>
                    <th>am/is/are</th>
                    <th>will be</th>
                </tr>
                <tr>
                    <th>Есть результат</th>
                    <th>был до тогда</th>
                    <th>have/has been</th>
                    <th>побуду до тогда</th>
                </tr>

            </table>
        </div>
    </div>

    <div class="container block">

        <div class="block_left">
            <form action="{% url 'add_phrase' dict.id %}" method="POST">
                {% csrf_token %}
                <input type="text" size="40" autofocus required placeholder="Eng words" name="engphrase">
                <div class="exemple">
                    <div class="left_inner">
                        <select list>
                            <option list>Phrase</option>
                        </select>
                    </div>
                    <div class="center">
                        <p><input type="checkbox">Золотой слиток</p>
                    </div>
                </div>
                <input type="text" size="40" autofocus required placeholder="Translate" name="translate">
                <p><input type="submit" value="add"></p>
            </form>
        </div>

        <div class="block_right">

            <div class="block_text">
                {% for phr in dict.phrase_set.all %}
                    <h5>{{ phr.engphrase }}</h5>
                    <p title="{{ phr.translate }}" align="right">translate</p>
                {% endfor %}
            </div>
        </div>

    </div>
</div>
{% endblock content %}

templates/include/footer.html
<!-- Sprite -->
<svg style="display: none;">

    <symbol id="facebook" viewBox="0 0 430.113 430.114">
        <g>
            <path d="M158.081,83.3c0,10.839,0,59.218,0,59.218h-43.385v72.412h43.385v215.183h89.122V214.936h59.805
                c0,0,5.601-34.721,8.316-72.685c-7.784,0-67.784,0-67.784,0s0-42.127,0-49.511c0-7.4,9.717-17.354,19.321-17.354
                c9.586,0,29.818,0,48.557,0c0-9.859,0-43.924,0-75.385c-25.016,0-53.476,0-66.021,0C155.878-0.004,158.081,72.48,158.081,83.3z"/>
        </g>
    </symbol>

    <symbol id="twitter" viewBox="0 0 612 612">
        <g>
            <path d="M612,116.258c-22.525,9.981-46.694,16.75-72.088,19.772c25.929-15.527,45.777-40.155,55.184-69.411
                c-24.322,14.379-51.169,24.82-79.775,30.48c-22.907-24.437-55.49-39.658-91.63-39.658c-69.334,0-125.551,56.217-125.551,125.513
                c0,9.828,1.109,19.427,3.251,28.606C197.065,206.32,104.556,156.337,42.641,80.386c-10.823,18.51-16.98,40.078-16.98,63.101
                c0,43.559,22.181,81.993,55.835,104.479c-20.575-0.688-39.926-6.348-56.867-15.756v1.568c0,60.806,43.291,111.554,100.693,123.104
                c-10.517,2.83-21.607,4.398-33.08,4.398c-8.107,0-15.947-0.803-23.634-2.333c15.985,49.907,62.336,86.199,117.253,87.194
                c-42.947,33.654-97.099,53.655-155.916,53.655c-10.134,0-20.116-0.612-29.944-1.721c55.567,35.681,121.536,56.485,192.438,56.485
                c230.948,0,357.188-191.291,357.188-357.188l-0.421-16.253C573.872,163.526,595.211,141.422,612,116.258z"/>
        </g>
    </symbol>

    <symbol id="linkedin" viewBox="0 0 430.117 430.118">
        <g>
            <path  d="M398.355,0H31.782C14.229,0,0.002,13.793,0.002,30.817v368.471
                c0,17.025,14.232,30.83,31.78,30.83h366.573c17.549,0,31.76-13.814,31.76-30.83V30.817C430.115,13.798,415.904,0,398.355,0z
                 M130.4,360.038H65.413V165.845H130.4V360.038z M97.913,139.315h-0.437c-21.793,0-35.92-14.904-35.92-33.563
                c0-19.035,14.542-33.535,36.767-33.535c22.227,0,35.899,14.496,36.331,33.535C134.654,124.415,120.555,139.315,97.913,139.315z
                 M364.659,360.038h-64.966V256.138c0-26.107-9.413-43.921-32.907-43.921c-17.973,0-28.642,12.018-33.327,23.621
                c-1.736,4.144-2.166,9.94-2.166,15.728v108.468h-64.954c0,0,0.85-175.979,0-194.192h64.964v27.531
                c8.624-13.229,24.035-32.1,58.534-32.1c42.76,0,74.822,27.739,74.822,87.414V360.038z M230.883,193.99
                c0.111-0.182,0.266-0.401,0.42-0.614v0.614H230.883z"/>
        </g>
    </symbol>
</svg>

<!-- Footer -->
<footer class="footer">
    <div class="container">

        <div class="footer_inner">
            <div class="footer_block">
                <h4 class="footer_title">Location</h4>
                <address class="footer_address">
                    <p style="margin: 0">English hope</p>
                    <p style="margin: 0";>www.happyhope.com</p>
                </address>
            </div>
            <div class="footer_block">
                <h4 class="footer_title">Contact</h4>
                <div class="social  social--footer">
                    <a class="social__item" href="https://vk.com/armahawdt" target="_blank">
                        <svg class="social__icon">
                            <use xlink:href="#facebook"></use>
                        </svg>
                    </a>
                    <a class="social__item" href="#" target="_blank">
                        <svg class="social__icon">
                            <use xlink:href="#twitter"></use>
                        </svg>
                    </a>
                    <a class="social__item" href="#" target="_blank">
                        <svg class="social__icon">
                            <use xlink:href="#linkedin"></use>
                        </svg>
                    </a>
                </div>
            </div>
            <div class="footer_block">
                <h4 class="footer_title">Information</h4>
                    <div class="footer_text">
                        <p>
                            Проект создан при помощи englishope<br>
                            ментор Надежда
                        </p>
                    </div>
            </div>
        </div> <!-- footer inner-->

    </div> <!-- / container -->
    <div class="copyright">
        <div class="container">
            <div class="copyright_text">
                <p>HAPPY HOPE</p>
                <span> by nurkin arman</span>
                <p>2020</p>
            </div>
        </div>
    </div>
</footer>

templates/include/header.html
<!-- Header -->
<header class="header">
    <div class="container">
        <div class="header_inner">
            <div class="logo">Eng</div>
            <nav class="nav">
                <a class="nav-link" href="#">About</a>
                <a class="nav-link" href="#">Contact</a>
                <a class="nav-link" href="#">Log In</a>
            </nav>
        </div>
    </div>
</header>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>EnglishPhrase</title>
    <link rel="stylesheet" href="css/style.css">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:
    wght@500&family=Roboto:wght@300&family=Work+Sans:ital,wght@1,300&display=swap" 
    rel="stylesheet">
</head>
<body>
<!-- Sprite -->
<svg style="display: none;">

    <symbol id="facebook" viewBox="0 0 430.113 430.114">
        <g>
            <path d="M158.081,83.3c0,10.839,0,59.218,0,59.218h-43.385v72.412h43.385v215.183h89.122V214.936h59.805
                c0,0,5.601-34.721,8.316-72.685c-7.784,0-67.784,0-67.784,0s0-42.127,0-49.511c0-7.4,9.717-17.354,19.321-17.354
                c9.586,0,29.818,0,48.557,0c0-9.859,0-43.924,0-75.385c-25.016,0-53.476,0-66.021,0C155.878-0.004,158.081,72.48,158.081,83.3z"/>
        </g>
    </symbol>

    <symbol id="twitter" viewBox="0 0 612 612">
        <g>
            <path d="M612,116.258c-22.525,9.981-46.694,16.75-72.088,19.772c25.929-15.527,45.777-40.155,55.184-69.411
                c-24.322,14.379-51.169,24.82-79.775,30.48c-22.907-24.437-55.49-39.658-91.63-39.658c-69.334,0-125.551,56.217-125.551,125.513
                c0,9.828,1.109,19.427,3.251,28.606C197.065,206.32,104.556,156.337,42.641,80.386c-10.823,18.51-16.98,40.078-16.98,63.101
                c0,43.559,22.181,81.993,55.835,104.479c-20.575-0.688-39.926-6.348-56.867-15.756v1.568c0,60.806,43.291,111.554,100.693,123.104
                c-10.517,2.83-21.607,4.398-33.08,4.398c-8.107,0-15.947-0.803-23.634-2.333c15.985,49.907,62.336,86.199,117.253,87.194
                c-42.947,33.654-97.099,53.655-155.916,53.655c-10.134,0-20.116-0.612-29.944-1.721c55.567,35.681,121.536,56.485,192.438,56.485
                c230.948,0,357.188-191.291,357.188-357.188l-0.421-16.253C573.872,163.526,595.211,141.422,612,116.258z"/>
        </g>
    </symbol>

    <symbol id="linkedin" viewBox="0 0 430.117 430.118">
        <g>
            <path  d="M398.355,0H31.782C14.229,0,0.002,13.793,0.002,30.817v368.471
                c0,17.025,14.232,30.83,31.78,30.83h366.573c17.549,0,31.76-13.814,31.76-30.83V30.817C430.115,13.798,415.904,0,398.355,0z
                 M130.4,360.038H65.413V165.845H130.4V360.038z M97.913,139.315h-0.437c-21.793,0-35.92-14.904-35.92-33.563
                c0-19.035,14.542-33.535,36.767-33.535c22.227,0,35.899,14.496,36.331,33.535C134.654,124.415,120.555,139.315,97.913,139.315z
                 M364.659,360.038h-64.966V256.138c0-26.107-9.413-43.921-32.907-43.921c-17.973,0-28.642,12.018-33.327,23.621
                c-1.736,4.144-2.166,9.94-2.166,15.728v108.468h-64.954c0,0,0.85-175.979,0-194.192h64.964v27.531
                c8.624-13.229,24.035-32.1,58.534-32.1c42.76,0,74.822,27.739,74.822,87.414V360.038z M230.883,193.99
                c0.111-0.182,0.266-0.401,0.42-0.614v0.614H230.883z"/>
        </g>
    </symbol>
</svg>

<!-- Header -->
<header class="header">
    <div class="container">
        <div class="header_inner">
            <div class="logo">Eng</div>
            <nav class="nav">
                <a class="nav-link" href="#">About</a>
                <a class="nav-link" href="#">Contact</a>
                <a class="nav-link" href="#">Log In</a>
            </nav>
        </div>
    </div>
</header>

<div class="intro">
    <div class="container">
        <div class="intro_inner">
            <h2 class="intro_title">Happy Hope</h2>
        </div>
        <div class="intro_table">
            <table class="sub_table" border="1px">
                <tr>
                    <th></th>
                    <th>past simple</th>
                    <th>present simple</th>
                    <th>future simple</th>
                </tr>
                <tr>
                    <th>Вообще просто <br> происходит</th>
                    <th>was/were</th>
                    <th>am/is/are</th>
                    <th>will be</th>
                </tr>
                <tr>
                    <th>Есть результат</th>
                    <th>был до тогда</th>
                    <th>have/has been</th>
                    <th>побуду до тогда</th>
                </tr>

            </table>  
        </div>
    </div>

    <div class="container block">

        <div class="block_left">
            <form action="#" method="POST">
                <input type="text" size="40" autofocus required placeholder="Eng words">
                <div class="exemple">
                    <div class="left_inner">                
                        <select list>
                            <option list>past simple</option>
                            <option list>present simple</option>
                            <option list>future simple</option>
                            <option list>past countinious</option>
                            <option list>present countinious</option>
                            <option list>future couutinious</option>
                            <option list>Other phrase</option>
                        </select>
                    </div>
                    <div class="center">
                        <p><input type="checkbox">Золотой слиток</p>
                    </div>
                </div>
                <input type="text" size="40" autofocus required placeholder="Translate">
                <p><input type="submit" value="add"></p>
            </form>
        </div>

        <div class="block_right">
     
            <div class="block_text">
                <h4>HI</h4>
                <p>
                    English texts for beginners to practice reading and comprehension 
                    online and for free.
                     Practicing your comprehension of written English will both improve
                      your vocabulary and understanding of grammar and word order. The 
                      texts below are designed to help you develop while giving you 
                      an instant evaluation of your progress.
                    Prepared by experienced English teachers, the texts, articles
                     and conversations are brief and appropriate to your level of 
                     proficiency. Take the multiple-choice quiz following each text, 
                     and you'll get the results immediately. You will feel both challenged 
                     and accomplished! You can even download (as PDF) and print the 
                     texts and exercises. It's enjoyable, fun and free. Good luck! 
                </p>
            </div>
        </div>
        
    </div>
</div>

<!-- Footer -->
<footer class="footer">
    <div class="container">

        <div class="footer_inner">
            <div class="footer_block">
                <h4 class="footer_title">Location</h4>
                <address class="footer_address">
                    <p style="margin: 0">English hope</p>
                    <p style="margin: 0";>www.happyhope.com</p>
                </address>
            </div>
            <div class="footer_block">
                <h4 class="footer_title">Contact</h4>
                <div class="social  social--footer">
                    <a class="social__item" href="https://vk.com/armahawdt" target="_blank">
                        <svg class="social__icon">
                            <use xlink:href="#facebook"></use>
                        </svg>
                    </a>
                    <a class="social__item" href="#" target="_blank">
                        <svg class="social__icon">
                            <use xlink:href="#twitter"></use>
                        </svg>
                    </a>
                    <a class="social__item" href="#" target="_blank">
                        <svg class="social__icon">
                            <use xlink:href="#linkedin"></use>
                        </svg>
                    </a>
                </div>
            </div>
            <div class="footer_block">
                <h4 class="footer_title">Information</h4>
                    <div class="footer_text">
                        <p>
                            Проект создан при помощи englishope<br>
                            ментор Надежда 
                        </p>
                    </div>
            </div>
        </div> <!-- footer inner-->

    </div> <!-- / container --> 
    <div class="copyright">
        <div class="container">
            <div class="copyright_text">
                <p>HAPPY HOPE</p>
                <span> by nurkin arman</span>
                <p>2020</p>
            </div>
        </div>
    </div>
</footer>

</body>
</html>